#!/bin/bash
#this script completes the steps needed after the git clones for the front end and pipeline

# define the front end directory full path name
front_end_dir=/home/ubuntu/bitbucket/scripts/front-end

# save current dir
prev_dir=$(pwd)

#git clone ​https://github.com/litaochen/e599-front-end
cd ${front_end_dir}
npm install
cd ..

#git clone git@bitbucket.org​:harvardcapstone/scripts.git
./pipeline/scripts/build_pipelines.bash

cd ${prev_dir}
