#!/bin/bash

# install the Ubuntu packages needed by swift
sudo apt-get -y install clang
sudo apt-get -y install libcurl3 libpython2.7 libpython2.7-dev libicu-dev
sudo apt-get -y install libcurl4-openssl-dev
sudo apt-get -y install openssl
sudo apt-get -y install libssl-dev

# define the swift directory full path name
swift_dir=/home/${USER}/bitbucket/server/swift

# create the swift directory
mkdir -p ${swift_dir}

# cd to the swift directory
cd ${swift_dir}

# get the swift installer
wget https://swift.org/builds/swift-4.2.1-release/ubuntu1804/swift-4.2.1-RELEASE/swift-4.2.1-RELEASE-ubuntu18.04.tar.gz

# untar the swift installer
tar xzf ./swift-4.2.1-RELEASE-ubuntu18.04.tar.gz

# define the .bashrc file name for this user
bashrc_file_name=/home/${USER}/.bashrc

# if the .bashrc file exists (may not exist if this is the root user)
if [[ -f ${bashrc_file_name} ]]
then
    echo "" >> ${bashrc_file_name}
    echo "# The following line was added by the imaging workflow installer" >> ${bashrc_file_name}
    echo "export PATH=${swift_dir}/swift-4.2.1-RELEASE-ubuntu18.04/usr/bin:$PATH" >> ${bashrc_file_name}
fi

# put swift on the path for this session
export PATH=${swift_dir}/swift-4.2.1-RELEASE-ubuntu18.04/usr/bin:${PATH}

# cd to the server project directory
cd ..
#cd Source

# build the server
swift package init --type library
swift build
